### ISSUE TITLE
ResizeObserver.eval

### ISSUE THREAD

**Issue by EnioSAF** [decades404/react-pixelart-face-card#1]
Hi,

I'm using your package on my application, it work really well and fit really nicely with my site !
Sadly, I have a weird problem with it.
I'm trying to emulate Windows 95 on my website so all my windows are popups made with React-RND and you can open, close and drag them without loading/refreshing the page.

![image](https://github.com/decades404/react-pixelart-face-card/assets/98952049/a1c5576c-3f70-420c-adad-6e01ef098593)

Unfortunately, when one of my composant have your package in it, if I happen to close the window where your package reside, it will throw me an error :
```
Unhandled Runtime Error
TypeError: Cannot read properties of null (reading 'parentElement')

Call Stack
ResizeObserver.eval
node_modules\react-pixelart-face-card\dist\react-pixelart-face-card.esm.js (38:0)
```

Do you have any idea why this is hapenning or why does it happen ?
Thank you very much !

**Comment by rolitodev** [comment]
Hi @EnioSAF, we just reviewed the method and noticed that when the window is closed, the face no longer appears. Therefore, we are going to make the adjustment so that you don't encounter the error again.

Greetings.

**Comment by rolitodev** [comment]
@EnioSAF You can update the library to the latest version (1.1.9) so you don't get the error anymore.

let's rocks.
